### ISSUE TITLE
Composer V2 support for providers-api

### ISSUE THREAD

**Issue by akondas** [repman-io/repman#109]
Some minor changes are needed:

- [x] proxy support for `metadata-url` (this is done in #100, thanks to @sadortun)
- [ ] proxy support for `providers-api` (optional)
- [x] repo support for `metadata-url`
- [ ] repo support for `providers-api` (optional)

**Comment by akondas** [comment]
Repman is now compatible with Composer V2 but for full support we must implement `providers-api`: https://github.com/composer/composer/blob/master/UPGRADE-2.0.md#providers-api

**Comment by akondas** [comment]
Composer v2 is supported, and `providers-includes` can be skipped as mention in #308.

**Comment by giggsey** [comment]
providers-includes != providers-api ?
