### ISSUE TITLE
Feature request: REST API to manage packages

### ISSUE THREAD

**Issue by binaryfire** [repman-io/repman#114]
Would love to have a REST API to add / remove repos programmatically! As well as list currently connected repos

**Comment by akondas** [comment]
Ha, waited for this thread to appear, so we have it in the backlog, but at the moment I am not able to give the date, but stay tuned :wink:

**Comment by urielbeaupre** [comment]
Also could we have the possibility of adding/removing tokens via the REST API?

**Comment by akondas** [comment]
yes, such basic functionalities will definitely be covered by REST API :wink:

**Comment by akondas** [comment]
REST API implemented and released in v 1.0.0. You can find api docs here:
https://repman.io/docs/api/#reference

Thanks for idea and feedback :wink:
