### ISSUE TITLE
Token revocation after leaving an external organisation

### ISSUE THREAD

**Issue by luckyraul** [repman-io/repman#120]
If someone leaves Github/Bitbucket/any oAuth organisation how do you handle this situation and block acccess ?

**Comment by akondas** [comment]
Currently the organization has one owner, so this situation means no synchronization possible. Soon we will add support for members (#56) of the organization, then you will be able to change the owner and use the other user's token. However, this is not the target state.

Ultimately, we intend to add a layer of provider (GitHub, GitLab, Bitbucket) integration, where the addition of integration will involve the provision of access configuration and then such integration will be able to live independently of the members.

**Comment by akondas** [comment]
With #56 and #106 you can now change organization owner and link new token. In case of problems or any other questions please re-open this issue or create a new one.

**Comment by luckyraul** [comment]
@akondas No, you don't understand the issue. For example:  We have user A and B in any oauth provider(GITLAB). They log-in into Repman, create accounts, create repman's token. They can use token

**Comment by akondas** [comment]
Thanks for your attention, in that case I would like to be able to understand it better. There are two options on the organization's token list: regeneration or permanent removal. Is it not enough to make one of them in such a case?
![Screenshot from 2020-05-08 07-52-48](https://user-images.githubusercontent.com/8239917/81375106-12862f00-9101-11ea-9a41-3edb3ea1ca12.png)

**Comment by luckyraul** [comment]
Yes, Except one problem - it should be done manually. Any chance to verify user while auth with Repman's token?

**Comment by akondas** [comment]
At present, Repman tokens are organization tokens that are independent of the members of the organization and the individuals who use them. What you write about would require at least two things (at least I understand it that way):

- [ ] direct mapping of provider's organization members with organization members in the repman
- [ ] assigning generated tokens directly to organization members in repman

In this way, we could track changes in the organization (provider) and remove the token of people who left the organization (provider). Technically it is possible, but as you can see it requires at least two serious features.

correct if I'm wrong :wink:

**Comment by luckyraul** [comment]
Looks correct
