### ISSUE TITLE
Pulling in github package using git@ gets stuck

### ISSUE THREAD

**Issue by ProxiBlue** [repman-io/repman#124]
Hello,

Accidentally pulled a public git repo using the git ssh url:
git@github.com:ProxiBlue/Magento-2-Product-Images-Order-View-.git

That has now locked up the package install, and the package is just sitting syncing, and never quits or completes.

So, I tried to use the https:// git url, adding teh same package (yes it allowed me), but even that is stuck.

So, in general, I think something is broke.

Note: I had this package in the packages listed, but update did not work - claimed no updates, so I deleted, and retried from scratch - ended up in above result.

**Comment by akondas** [comment]
My fault, I am so sorry. Unfortunately due to incorrect configuration the consumer stopped and the queue was not processed. At this point, consumers have resumed and everything should be back to normal.

**Comment by ProxiBlue** [comment]
It happens, thanks for getting back up.

**Comment by danharper83** [comment]
I seem to have this issue at the moment, I imported a package and it is just sat synching and no actions are available to remove it.
