### ISSUE TITLE
Checksum verification failed, 404

### ISSUE THREAD

**Issue by Radiergummi** [repman-io/repman#139]
`composer install` fails due to errors with packages hosted on repman.io. The log shows the following:

```
  - Installing messengerpeople/specification-database (v1.1.1): Downloading
 Failed, trying the next URL (404: The "https://ourhandle.repo.repman.io/dists/ourhandle/packagename/1.1.1.0/a8b7d5c6d095fb50e07fc5e420f45164513902ca.tar" file could not be downloaded (HTTP/1.1 404 Not Found))Downloading    Failed to download ourhandle/packagename from dist: The "https://api.github.com/repos/ourhandle/packagename/zipball/a8b7d5c6d095fb50e07fc5e420f45164513902ca" file could not be downloaded (HTTP/1.1 404 Not Found)
```
This is probably similar to #84, but our versions never contain slashes but look like `v1.2.3` instead. It's also similar to #67, but the error does occur for the repman.io sources too, not only for GitHub.  
As @akondas pointed out in #67, we do have checksums in the lock file, but composer seems to insert it automatically.  

As we have multiple engineers working together, I suspect one of them has an older composer version that causes the "broken" lockfile. Specifically, the last one who committed a lockfile change in one of our projects had `1.8.0` installed. His lockfile looked like this:
```json
{
    "name": "ourhandle/packagename",
    "version": "v1.1.1",
    "source": {
        "type": "git",
        "url": "git@github.com:ourhandle/packagename.git",
        "reference": "a8b7d5c6d095fb50e07fc5e420f45164513902ca"
    },
    "dist": {
        "type": "tar",
        "url": "https://api.github.com/repos/ourhandle/packagename/zipball/a8b7d5c6d095fb50e07fc5e420f45164513902ca",
        "reference": "a8b7d5c6d095fb50e07fc5e420f45164513902ca",
        "shasum": "e098ed99b0e445508105b9256d15baf648c9b907",
        "mirrors": [
            {
                "url": "https://ourhandle.repo.repman.io/dists/%package%/%version%/%reference%.%type%",
                "preferred": true
            }
        ]
    },
```

Executing `composer install` with this file causes the installation to fail due to the above mentioned error. If I do `composer update` however, the lockfile is updated to the following:
```json
{
    "name": "ourhandle/packagename",
    "version": "v1.1.1",
    "source": {
        "type": "git",
        "url": "git@github.com:ourhandle/packagename.git",
        "reference": "a8b7d5c6d095fb50e07fc5e420f45164513902ca"
    },
    "dist": {
        "type": "zip",
        "url": "https://api.github.com/repos/ourhandle/packagename/zipball/a8b7d5c6d095fb50e07fc5e420f45164513902ca",
        "reference": "a8b7d5c6d095fb50e07fc5e420f45164513902ca",
        "shasum": "",
        "mirrors": [
            {
                "url": "https://ourhandle.repo.repman.io/dists/%package%/%version%/%reference%.%type%",
                "preferred": true
            }
        ]
    },
```

Diff being the `dist.type` being `zip` instead of `tar` and `dist.shasum` being empty in the working configuration. 

---

Sorry for the long issue. So the actual question is - was there any known change in checksum handling in newer composer versions? And by extension, is repman.io incompatible with older versions? That would be an interesting requirement to show in the Readme.

**Comment by akondas** [comment]
Hello @Radiergummi, I would like to help solve this problem. Does this package really exist at `https://api.github.com/repos/ourhandle/packagename/zipball/a8b7d5c6d095fb50e07fc5e420f45164513902ca`? (I do not mean authentication, but whether the addresses are correct)

**Comment by Radiergummi** [comment]
Yes, the package exists, but unless using a token, GitHub will return a 404 instead of the redirect to codeload.github.com.

**Comment by akondas** [comment]
Have the packages been added like the "GitHub" type? It supports authentication using a private token.

**Comment by Radiergummi** [comment]
Yes, I added the package via `/package/new/github` and followed the OAuth flow. In the end I could select our private packages from the dropdown.

**Comment by akondas** [comment]
If authorization is not a problem, I bet that it is `tar` format. At the moment I will try to recreate this way and find a solution. It seems to me that Repman downloads and saves everything as a zip, so that's probably why it's 404.

**Comment by Radiergummi** [comment]
Would it make sense to generate a tar from the zip when initially downloading the package? So Repman would just provide both? Something like 
```php
$packageArchive = new PharData($pathToZipFile);
$legacyPackageArchive = $packageArchive->convertToData(Phar::TAR);
```

**Comment by akondas** [comment]
Yes, we can do it, but I think it is better to do it simply on demand, because it will be a rare case. Only when someone asks for such a resource will we convert.

Can you write what package did you use in the example?

**Comment by Radiergummi** [comment]
That's a built-in class actually: [php.net/manual/en/class.phardata.php](https://www.php.net/manual/en/class.phardata.php).

> Because these archives do not contain a stub and cannot be executed by the phar extension, it is possible to create and manipulate regular zip and tar files.

**Comment by akondas** [comment]
Tar files will be supported, I'm working on a fix. Regarding the problem of verifying the checksum, let's move this thread to #153

**Comment by akondas** [comment]
Hey @Radiergummi, I tested repman with tar packages and everything works fine.
For checksum problems with github repos I recommend to run `composer update --lock`

**Comment by Radiergummi** [comment]
Hey @akondas, my solution was to force the entire team to use the latest composer version, delete all lock files and start fresh :) Everythings fine now, thank you nevertheless!
