### ISSUE TITLE
 /login not found + There are no commands defined in the "proxy:domain" namespace.

### ISSUE THREAD

**Issue by bash-stack** [repman-io/repman#154]
after manual install , and migrations , at the proxy-setup step:

` There are no commands defined in the "proxy:domain" namespace.`

Also  the / page redirects to `/login` and this gives a 404

**Comment by akondas** [comment]
`proxy:domain` is command from Symfony CLI: https://symfony.com/download. Setting up subdomains in this way is rather mainly for development purposes. Production should be a redirection with an wildcard (for example at dns level). You can read more in docs: https://repman.io/docs/standalone/#dns-records

As for the second problem, the question is how is the application served (nginx, local php server or something else)?

**Comment by bash-stack** [comment]
apache+php7.4fpm behing nginx proxy

**Comment by bash-stack** [comment]
found it  , the "normal" nginx config makes the index.php/ORIGINALURL redirection , 

so a .htaccess containing the following lines in the public dir helped 

```
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ /index.php/$1 [NC,L,QSA]
```

**Comment by bash-stack** [comment]
found it  , the "normal" nginx config makes the index.php/ORIGINALURL redirection , 

so a .htaccess containing the following lines in the public dir helped 

```
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ /index.php/$1 [NC,L,QSA]
```
