### ISSUE TITLE
private repositories from custom gitlab pulled without auth  ( fails with 401)

### ISSUE THREAD

**Issue by bash-stack** [repman-io/repman#158]
When trying to add a package from own gitlab  :

* the names of the repositories are listed (API) 
* but when repman tries to sync , it requests "upload-package" , without user credentials ( aka anonymous pull) 
Gitlab Response is 401 

→ using a git `https://username:token@gitlab.instance:123/path/to/repo.git` URL as workaround 

GitLab Log Output
```
 Parameters: {"service"=>"git-upload-pack", "namespace_id"=>"mygroup", "repository_id"=>"hereistherepo.git"}
Filter chain halted as :authenticate_user rendered or redirected
Completed 401 Unauthorized in 23ms
```

**Comment by akondas** [comment]
Yes, it is a bug in `ComposerPackageSynchronizer`, for gitlab packages authorization is hardcoded for `gitlab.com`. We will fix it asap :wink:

**Comment by bash-stack** [comment]
gets stuck now ( #165 )
