### ISSUE TITLE
repman uses /root/.composer/cache/ for checkout

### ISSUE THREAD

**Issue by bash-stack** [repman-io/repman#164]
even when running as www-data ( also installed as www-data) , git version uses /root/.composer/cache/

**Comment by akondas** [comment]
Can we write here what problems it generates?

**Comment by benchonaut** [comment]
permission denied errors on /root/.composer/cache/vcs unless one chmod's at least +rx for dirs and +wx for cache directory

**Comment by bash-stack** [comment]
> Can we write here what problems it generates?
 access denied on /root/.composer/cache/vcs unless one chmod*s at least +rx on the folders and +rw on the cache directory  for the web server user ( here www-data ) in self hosted variant

**Comment by akondas** [comment]
In fact, this can be a problem because we've always assumed isolation work (separate instance or docker). I will see what could be done in this matter.

Question from curiosity, what are the reasons for manual repman installation (instead of using one of the ready variants, for example ansible or docker)?.

**Comment by bash-stack** [comment]
Having frontend proxies already and a standardized container which  handles x-forwarded-for as real IP and offers per container busybox .. and trying to have a public machine since original composer speed just s**cks

**Comment by akondas** [comment]
Hey @bash-stack, is this issue still a problem or can we close this for the moment?

**Comment by akondas** [comment]
I close because of the lack of further information. If necessary, please open issue again.
