### ISSUE TITLE
Containers app and consumer constantly failing when APP_HOST is changed

### ISSUE THREAD

**Issue by i-mihaylov** [repman-io/repman#169]
Hi guys,

I don't know if it is only me, but when I change the APP_HOST to something different than repman.wip I constantly get
this error:
![repman_1](https://user-images.githubusercontent.com/9304226/82544495-baa9e800-9b44-11ea-98f6-a32d45d6bb6a.png)
![repman_2](https://user-images.githubusercontent.com/9304226/82544511-bed60580-9b44-11ea-870d-e84e27be216a.png)

Thanks

**Comment by karniv00l** [comment]
Hi,

It's because you've set `APP_ENV` to `dev` and there are no dev packages installed in docker image (https://github.com/repman-io/repman/blob/master/Dockerfile#L44).

**Comment by i-mihaylov** [comment]
@karniv00l , thank you for the quick response. That was it. Changed APP_ENV to prod and now it started just fine.
