### ISSUE TITLE
New release with option to disable registration

### ISSUE THREAD

**Issue by realshadow** [repman-io/repman#187]
Hey,

I am very interested in the option to disable registration. Would it be possible to release it in a new docker image?

Regards

**Comment by akondas** [comment]
Yes, it is currently available in the `latest` tag. In addition, in this week a stable version 0.3.0 will be released in which this feature will be available (with security scanner for your private packages).

**Comment by realshadow** [comment]
Thanks for the info. In the meantime I mounted current master into the container, works like a charm. 

Speaking of security scanner, I had two problems with it, nothing major - just for info:
 - some of ours packages do not have lock file so the security scanner failed with an error, this should maybe trigger a warning?
 - one of the packages had a security warning, but the tooltip started "blinking" (it was created and destroyed in DOM every milisecond)

**Comment by karniv00l** [comment]
Hi @realshadow 

> * some of ours packages do not have lock file so the security scanner failed with an error, this should maybe trigger a warning?

we actually use *warning* as a security warning and *error* for scan problems, I guess we would have to add new status like "skipped" maybe

> * one of the packages had a security warning, but the tooltip started "blinking" (it was created and destroyed in DOM every milisecond)

can you maybe reproduce that?

**Comment by realshadow** [comment]
Hey @karniv00l,

 - let me try to describe it better - the problem I had was that I thought the synchronisation process failed with an error and I had to look in the code to see which part threw the error. As I didnt have time to figure out what runs when, I just disabled the security scanner directly in code. So the UI in the regard seems a bit confusing - maybe it would be better to display two columns one for sync and one for security scanner or consolidate the status somehow or display more verbose message why this had happened, what do you think?
 - the same thing happens in the cloud version, you can use [this repository](https://github.com/realshadow/satis-control-panel) - it has bunch of security warnings since "it works" and I dont really maintain it, the tooltip is so huge it creates a scrollbar before it blinks away

**Comment by karniv00l** [comment]
Thanks for the example, I've prepared PR to mitigate this
