### ISSUE TITLE
Missing composer.lock reported as error

### ISSUE THREAD

**Issue by mbrodala** [repman-io/repman#189]
When adding a package without `composer.lock` Repman reports this as error:

![image](https://user-images.githubusercontent.com/5037116/83540064-1a66a280-a4f8-11ea-96a8-a8480258f2b2.png)

However, having a repository without `composer.lock` is perfectly valid, for example for library packages as well as avoiding issues with dependency overrides on CI build.

So IMO this should not be reported as error.

**Comment by karniv00l** [comment]
I agree. @akondas any thoughts?

**Comment by akondas** [comment]
Yes, package without `composer.lock` should not have `error` status. Maybe `missing` or `not applicable`? I also wonder if we can do the scan in any other way then?

**Comment by akondas** [comment]
Fixed in #191 
![Screenshot from 2020-06-05 10-24-25](https://user-images.githubusercontent.com/8239917/83854352-e2897600-a716-11ea-8bf7-bbc66da61127.png)

**Comment by mbrodala** [comment]
Thanks, after a re-scan the updated status is show. :+1:
