### ISSUE TITLE
Error after adding package

### ISSUE THREAD

**Issue by orfeeen** [repman-io/repman#193]
Hi!

I added my package from my gitlab self-hosted and i got error (see picture).

What should I do?

![image](https://user-images.githubusercontent.com/14373063/83800476-28f7ba00-a6b0-11ea-8eed-b5839bbcbf91.png)

**Comment by orfeeen** [comment]
Hm...
After command `bin/console repman:security:update-db` my problem has been resolved.

And what could be the problem?

**Comment by akondas** [comment]
It runs every two hours, so when you first install it you will have to start it manually. But maybe even before we release it we can throw it into the startup scripts. @karniv00l?
