### ISSUE TITLE
Synchronization error when importing repository from Bitbucket (preg_match)

### ISSUE THREAD

**Issue by nutellinoit** [repman-io/repman#202]
Hi, i have a problem with https://app.repman.io/ 

When importing the package from **gitlab (a public repository)** everything is fine, but if i import the same repository **(this time private) from bitbucket** , it fails:

![Screenshot 2020-06-21 at 18 48 03](https://user-images.githubusercontent.com/25492971/85230360-c1e83e00-b3ef-11ea-968b-4e8e0df7824e.png)

**Comment by akondas** [comment]
We will gladly help, but we must be able to reproduce this error to be able to move on with the topic.

**Comment by akondas** [comment]
Hello @nutellinoit, can you somehow share this problematic package with us? I would like to reproduce this problem and fix it.

**Comment by nutellinoit** [comment]
Hi @akondas , you can use this repository: https://gitlab.com/nutellino-playground/lemp-demo/library/common and make it private in bitbucket

**Comment by akondas** [comment]
@nutellinoit thanks for sharing. Still no issue. This was imported from private Bitbucket repository (I imported directly via the "Bitbucket" package type):
![Screenshot from 2020-07-20 08-13-28](https://user-images.githubusercontent.com/8239917/87905544-19b2ad00-ca61-11ea-86fd-3eaee98cf32a.png)

Maybe it is a specific branch or tag name that is not there now?

**Comment by akondas** [comment]
Hey @nutellinoit is this problem still occurring? I would like to be able to reproduce and repair it. Thanks for feedback :beers:

**Comment by nutellinoit** [comment]
Sorry for the delay @akondas , it seems resolved now! I did a test 5 minutes ago and it's working

**Comment by akondas** [comment]
Great :cocktail: and thanks for feedback :wink:
