### ISSUE TITLE
Issue with Amazon-Mailer package

### ISSUE THREAD

**Issue by nandogameiro** [repman-io/repman#206]
Hi there,

Just trying to setting up repman using docker, but I am getting an issue when trying to setup AWS SES using the package using DSN 
`MAILER_DSN=ses+api://$AWS_ACCESS_KEY:$AWS_SECRET_KEY@default?region=ap-southeast-2`

I've also tried `ses+https` , `ses+smtp` and no luck

The error is 
`Unable to send an email: The security token included in the request is invalid. (code 0).`

After doing some investigation look like the version  `5.0` of `amazon-mailer` which is included on the latest version o `repman` has been deprecated.

AWS SES has changed their API while ago and all the requests should use signature V4, while this deprecated version uses V3. They now require use AsyncAws 

https://github.com/symfony/amazon-mailer/blob/c880d1c0920d7dc7d63c74bfcfcddc209b4ed803/Transport/SesApiTransport.php#L24

The version `5.1` of `amazon-mailer` fixes this issue.

Any change to get the current version of amazon-mailer upgraded on this repo?

You can see some reference on the links below
https://github.com/symfony/symfony/issues/35468
https://github.com/symfony/symfony/pull/35992

Thank you

**Comment by akondas** [comment]
Hello, of course we can update mailer, I will take care of it soon. Have you tried `MAILER_DSN=ses://...`?
We are using it in our production instance and it works perfect.

**Comment by akondas** [comment]
Looks like we need to update Symfony to `5.1` ... but this issue will speed up this process :wink:

**Comment by nandogameiro** [comment]
> Hello, of course we can update mailer, I will take care of it soon. Have you tried `MAILER_DSN=ses://...`?
> We are using it in our production instance and it works perfect.

Hey @akondas, thanks to getting back to me! 
I've just tried to use `MAILER_DSN=ses://...` and didn't work, same error, maybe because I tried to pass the variable to `ap-southeast-2` where is my SES setup.

Thanks to looking at this issue. Appreciated it.

**Comment by PWalkow** [comment]
Will this fix that exist in 5.1 will be merged back to 4.4?

**Comment by akondas** [comment]
Hey @PWalkow, hard to say. You can ask this question in any of these issues.

@nandogameiro I have a fix prepared, but I still waiting for another error to be corrected, it seems that it has already been merged (https://github.com/symfony/symfony/pull/37440) but still there was no release until then

**Comment by nandogameiro** [comment]
Hey @akondas ,cool! thanks for actioning on this! Just waiting this get fixed to starting using repman! :)

**Comment by akondas** [comment]
Repman `0.6.0` released with symfony `5.1.5` :fireworks: 
https://github.com/repman-io/repman/releases/tag/0.6.0
