### ISSUE TITLE
Filesystem abstraction for all file related services

### ISSUE THREAD

**Issue by akondas** [repman-io/repman#228]
This is the summary thread for replacing the current implementation with `Filesystem`. It all started in #209 (thanks to @jonnyynnoj). Partly for the proxy, work has already been done (details in #221). Things to do:
- [ ] add `Filesystem` abstration to `PackageManager`
- [ ] remove `Storage` interface 
- [ ] add `Filesystem` abstraction to security scanner logic
- [ ] remeber to use streams instead of strings
- [ ] create example configuration for S3 and other popular storage options

**Comment by pedro-stanaka** [comment]
Hi @akondas I would be interested in developing this, is there a way to break down the work here? Seems like a lot of changes for one single MR. 

I still didn't dive deep into the code, but wouldn't it be okay for a first iteration to keep the `Storage` contract and implement the features regarding Filesystem abstraction "under the hood" (e.g. by creating a new implementation of type S3 for `Storage`). 

Please let me know how I can help. I want to deploy this to a Kubernetes cluster and would love to have the storage totally separate from the instance running the application and I would also like to avoid shared volumes.

**Comment by akondas** [comment]
Hi @pedro-stanaka, you can start with `PackageManager` and replace `Filesystem`, `AtomicFile` and other file related things.
Initially, we started by dividing the storage into a private part and a proxy, but since it can be easily done with directories (this is what it is done now), I would see that there is one filesystem for everything with an appropriate adapter (for example s3).

**Comment by pedro-stanaka** [comment]
I believe this is now closed, right?

**Comment by akondas** [comment]
Yes, will be preparing a release, we only need to add examples to the documentation.

**Comment by akondas** [comment]
Thanks for your help :beers:
