### ISSUE TITLE
Problem with authorization

### ISSUE THREAD

**Issue by josefsabl** [repman-io/repman#284]
Hello and thank you for this wonderful tool.

I am having problems with authorization though.

I RUN the suggested line in the Dockerfile of php-fpm I use to composer install.

`composer config --global --auth http-basic.https://myorganization.repo.repman.mycompany.cz token ab7.................fce`

I also tried to include this in the composer.json file (also the bearer token flavour)

```
{
      "type": "composer",
      "url": "https://myorganization.repo.repman.mycompany.cz",
      "options": {
        "header": [
          "Authorization: http-basic token ab7.................fce"
        ]
      }
    }
```

And I am trying to manually send request to the server:

```
GET https://myorganization.repo.repman.mycompany.cz/packages.json
Authorization: http-basic token ab7.................fce
```

or 

```
GET https://myorganization.repo.repman.mycompany.cz/packages.json
Authorization: bearer ab7.................fce
```

But to no avail and still am getting 403.

When I enable anonymous access for the organization the connection works so it's not something in infrastructure etc.

What am I doing wrong? :-)

Thank you for any help!

**Comment by josefsabl** [comment]
This works, my bad...

```
GET https://myorganization.repo.repman.mycompany.cz/packages.json
Authorization: Basic token ab7.................fce
```

I tried to solve it for like two hours and literally few seconds after posting this I noticed the typo :-D

But what is wrong with my Docker? ;-)

**Comment by akondas** [comment]
Hello @josefsabl, I'm glad you found a solution. But what is the problem with the docker?

**Comment by josefsabl** [comment]
Solution not found so far, but my observations were not correct and I indeed could "log in" by crafting request manually so it cannot be the problem with repman itself but with my setup. I am plainly not able to configure the composer to authenticate correctly.

My setup is:

- I am running Docker Desktop with WSL2 enabled.
- I have a container with php fpm that I use as remote interpreter from PhpStorm.
- I use this interpreter to run composer update.

Important parts from the dockerfile:

```
FROM php:7.4.10-fpm-alpine as php
RUN apk add --no-cache composer
RUN composer global require repman-io/composer-plugin
RUN composer config --global --auth http-basic.https://myorganization.repo.repman.mycompany.cz token ******************
```

I also tried the [auth.json](https://getcomposer.org/doc/articles/http-basic-authentication.md) technique.
I also tried setting the Authorization header manually [1](https://getcomposer.org/doc/05-repositories.md#stream-options) [2](https://getcomposer.org/doc/05-repositories.md#stream-options)

And as I am typing this, i realized i missed the most obvious option to add repository like this:

`https://token:**********************@myorganization.repo.repman.mycompany.cz`

Which works, regarding authentication!

This rubberducking method is amazing :-D

I will go back to those earlier methods and try to debug why they don't work.

However, sadly it still doesn't work. The 403 went away but now I am getting 500 when asking repman for standard packagist package. I will look into it.
