### ISSUE TITLE
GitLab Login with self-hosted GitLab

### ISSUE THREAD

**Issue by temp** [repman-io/repman#285]
When trying to log in with our self-hosted GitLab instance I always get "Username not found".
Guess it's because repman uses the email as the user identifier, but GitLab uses the Username? Or am I doing something wrong?

**Comment by akondas** [comment]
Hello @temp, the question is whether you registered first. Repman has an internal list of users and to log in using oauth you first need to create an account in the same way (click the Sign up link at the bottom of the login form).

**Comment by temp** [comment]
Ah ok. Is it possible to add the connection afterwards?

**Comment by akondas** [comment]
Currently no, but if the mail from repman matches the mail from gitlab (primary and confirmed), it should be able to log in this way.

**Comment by akondas** [comment]
And this connection changes nothing, internally nothing depends on this logic. Registration with a provider releases the user from the need to enter an e-mail. Besides, there is no difference :wink:

**Comment by temp** [comment]
Ah ok, thanks, nice catch. Email addresses differed, repman used our short form, gitlab the long form. After changing my email in the database, the gitlab-login-button works!
