### ISSUE TITLE
Add package from self-hosted GitLab allows duplicates

### ISSUE THREAD

**Issue by temp** [repman-io/repman#286]
A package can be added multiple time (in our case from a self-hosted GitLab instance).
This leads to multiple webhooks being created. Is this the desired behaviour? I can't think of any usecase...

**Comment by temp** [comment]
Ok, just found out that the duplicate-error-message appears after the job is finished.
But now I have a package with "Error: Package ofcs/ofcs already exists. Package name must be unique within organization.", but I can't delete the package, there is only a "Update" button in the dropdown.
And the second webhook wasn't deleted...

**Comment by akondas** [comment]
In case of a synchronization error, it is possible to delete the package:
![Screenshot from 2020-09-24 08-51-21](https://user-images.githubusercontent.com/8239917/94110624-37c2d200-fe43-11ea-9761-e6307747fe3f.png)

Before synchronization, we are not able to determine if the package exists (we need to read the `composer.json` file). Therefore, it is only after synchronization that this error pops up.

**Comment by akondas** [comment]
I forgot to add:
Currently, only the owner of the organization can delete packages.

**Comment by temp** [comment]
Thanks for the clarification, I was indeed not the owner.
