### ISSUE TITLE
Limit number of releases?

### ISSUE THREAD

**Issue by temp** [repman-io/repman#287]
We just added a large repository from our self-hosted GitLab, it has about 1500 tags (yes, it's a rather old project...).
repman wants to create a zip for every tag, which will end in 1500 zips with each 50 mb, resulting in 75 gb of release-zips, of which the first 1499 will never be used ;-)
Is there a way to restrict the number of historical releases that are handled?

**Comment by akondas** [comment]
Downloading all distributions ahead of time was purposeful (@karniv00l maybe you remember why?). In fact, this use case complicates things a bit. We could make a separate option in the instance settings to help with this:

`Download dist on sync` - if yes then all distibution will be downloaded during synchronization, if no, only metadata (version history) will be downloaded. Default option will be `no`.

Let me know what you think.

**Comment by temp** [comment]
Would work for me!
What I did on our instance was delete all old zips by hand... I know, not an ideal solution, but at least the storage didn't explode :-D

**Comment by temp** [comment]
But this should be configurable during package-add...

**Comment by akondas** [comment]
Hey @temp, we are almost at the end:
![Screenshot from 2020-10-08 08-40-00](https://user-images.githubusercontent.com/8239917/95423759-ebe35300-0941-11eb-83f8-7d288d75acd3.png)

@karniv00l one more thing:
- [ ] allow to update this limit

**Comment by giggsey** [comment]
@karniv00l Should #294 limit what's shown on the UI or the latest release?

I think the serialised metadata itself is fine, just the DB stored data.

Syncing 3 releases of https://github.com/symfony/finder.git provides:
![image](https://user-images.githubusercontent.com/305730/95866389-c39f8e00-0d5f-11eb-917d-21ab9758c512.png)
![image](https://user-images.githubusercontent.com/305730/95866603-06616600-0d60-11eb-9e20-fe9f994552cf.png)

(Top screenshot app.repman.io, bottom local). Both added with same URL + package restrictions today.

**Comment by karniv00l** [comment]
@giggsey we are limiting number of versions and distributions files, this includes dev and stable releases.I will look into this, thanks

**Comment by temp** [comment]
Just upgrade to 1.1.0, and will try the feature now. What happens when I limit the releases afterwards? Will it throw away the obsolete releases?

**Comment by karniv00l** [comment]
@temp It will remove old releases

**Comment by temp** [comment]
Awesome, thanks! Works fine for me!
... Job just finished, all old releases are gone, and storage was freed. Great work!
