### ISSUE TITLE
Allow to change timezone in instance configuration

### ISSUE THREAD

**Issue by sadortun** [repman-io/repman#296]
Hi,

I really like to be ahead of schedules :) But i find it strange that i've pushed a release "in 3 hours" :) 

![image](https://user-images.githubusercontent.com/794449/95029878-907f3f80-0679-11eb-8e97-8324e2407a38.png)

We all love timezones :) 

Have a great day,
Samuel

**Comment by akondas** [comment]
Repman - predicts when you do release :joy: 

We could give the option to change the time zone in the instance settings.

**Comment by giggsey** [comment]
Could this be a user setting too? For teams distributed around the globe.

**Comment by akondas** [comment]
We can just make this option this way only. So each user can select own timezone ... but in this way we must provide timezone list :thinking:

**Comment by sadortun** [comment]
I haven't look any deeper in this, but ...  Would it be simply my php.timezone Ini config wrong ? 

Not sure timezones are required if you display release times as  relative time.

**Comment by akondas** [comment]
Sure, we can display exact date and time (with timezone), but this relative reference was supposed to make it easier. On the other hand, when you hover the mouse over the release text you can see the exact date:
![Screenshot from 2020-10-07 08-27-08](https://user-images.githubusercontent.com/8239917/95295201-ea992400-0876-11eb-8c91-8f64c1aa41d1.png)

**Comment by akondas** [comment]
Looks like we are going live with this feature (thanks to @karniv00l). @giggsey and @sadortun please check and if possible, please give me feedback :wink:

**Comment by akondas** [comment]
Now that this is already implemented, I think we can close this thread. If anyone has any comments or feedback, please feel free to write or reopen.
