### ISSUE TITLE
Synchronizing takes to long and could not import from Toran Proxy

### ISSUE THREAD

**Issue by mostafasoufi** [repman-io/repman#311]
I'm using the Toran Proxy and want to import the packages into the Repman but unfortunately could not import and takes too long.

![screenshot-packagist codelight eu-2020 10 20-17_08_52](https://user-images.githubusercontent.com/701520/96598032-214f4f80-12f7-11eb-9001-886faee0d83a.png)

Some of the packages have the custom repository:

```
"repositories": [{
        "type": "composer",
        "url": "https://packages.domain.com/repo/private/"
    },
    {
        "type": "composer",
        "url": "https://packages.domain.com/repo/packagist/"
    }
],
```

**Comment by mostafasoufi** [comment]
I tested with a default GitHub package, still didn't work.

**Comment by karniv00l** [comment]
Hi @mostafasoufi, how is your Repman setup? Can you confirm that consumer is working?

**Comment by mostafasoufi** [comment]
It's self-hosted, nginx and php-fpm. I've checked permissions as well and there are no logs.

**Comment by karniv00l** [comment]
Please have a look at #73

**Comment by akondas** [comment]
Is the consumer runnig? You need to run background task: `bin/console messenger:consume async`.
Pleas look at `supervisor` role in ansible or `docker-compose.yml` `consumer` container.

If problem still occurs you can check:
- [ ] Failed message queue: `bin/console messenger:failed:show`
- [ ] Message consumer logs `var/log/consumer.log`
- [ ] Supervisor logs `/var/log/supervisor/message-consumer_00-stderr`

**Comment by mostafasoufi** [comment]
Thanks, I forgot to do **Workers** commands.
https://symfony.com/doc/current/messenger.html#deploying-to-production

**Comment by akondas** [comment]
@mostafasoufi Thanks for info.
@karniv00l This should be better documented. It's not the first time we have had such a problem, it would be worth adding to the docs. 

Second, we can also start building a FAQ or troubleshooting section there. We will describe the most frequent problems and how to deal with them (where to look for logs, etc.)
