### ISSUE TITLE
I broke my org in the cloud service

### ISSUE THREAD

**Issue by lhilton** [repman-io/repman#324]
I messed up a couple of orgs in learning the cloud platform. Both of these URL's 404 on the site. It looks like the URL field isn't a URL field? Maybe it's a slug? Either way, I cannot access these orgs to update or delete them.

https://app.repman.io/organization/complyant.co/settings

https://app.repman.io/organization/https://complyant.co/overview

**Comment by akondas** [comment]
Hello @lhilton, yes this is an alias. Right now I can see that there is a bug that allowed this field to be invalid. It will be fixed. I temporarily changed the alias of your organization. Everything should work now.
