### ISSUE TITLE
Wpackagist support?

### ISSUE THREAD

**Issue by sirolf** [repman-io/repman#360]
Hi,

At the moment we use satis to create private packagist. we also grab a lot of packages from wpackagist.org (wordpress plugins / themes).

Is there a way to add these wordpress packages to repman?

**Comment by akondas** [comment]
Not yet, but this idea is already on our backlog. Thanks for your feedback, more submissions like this will put this task higher on the priority list :wink:

**Comment by a-camacho** [comment]
I would also like to add a sumission for this feature.
It is good to be able to use repman to contain some packages from packagist and wpackagist to use often.

**Comment by robbinschut** [comment]
I would like to have this feature too!
