### ISSUE TITLE
How to allow for Horizontal Scalability

### ISSUE THREAD

**Issue by pedro-stanaka** [repman-io/repman#372]
The application as it stands does not allow for HA, it is using some resources that are not shared like:

- Sessions
- Cache

If possible, could you briefly go over how you scale this application on your environment (repman.io)?

I did some experiments with the repository and I saw that it is not possible to configure cache adapters with env, because it is in a Compiler pass. So, I would have a couple of questions:

- if anyone wanted to introduce different cache adapters, this person would have to keep a fork? 
- Is there any other way out of it? 
- Would you be inclined to add a new default adapter that is shared (redis, memcached, etc) or that is already too opinionated for the app?

**Comment by akondas** [comment]
Currently our public instance ([app.repman.io](https://app.repman.io)) use single EC2 instance and for now it's enough (over 1k users). In addition, the resources are covered with CloudFront, which will reduce the required amount of resources.

If there is a need for more machines, we can create appropriate environmental variables that will make it possible to deploy to more than one machine. There are actually two things to do (as you wrote):
- session
- cache

I am happy to accept such a pull request (or help if further discussion is needed).

**Comment by pedro-stanaka** [comment]
Thanks for the insights, sadly I don't know a way to configure the caching lawyer using envvars because they are in a compiler pass, so they break once you try to configure them with dynamic values. I will research more about that and if I can come up with a solution I will send a PR.

For now, I have to maintain my fork anyway to customize the docker images for my needs, so I will keep the configuration on my side. Thanks for the openness and sharing your setup! I will check whether I can use some CDN or cache lawyer to ease the load on the application itself.

**Comment by akondas** [comment]
If you have any resource issues at the moment, let us know (even a private message). I would like to know the limits of the Repman's capabilities in customer environments. Maybe something could be changed in the code itself or the functionality to improve the performance of the application.
