### ISSUE TITLE
Onboarding new user/organization

### ISSUE THREAD

**Issue by noniagriconomie** [repman-io/repman#381]
Hi 👋 

First of all thank you for this awesome projet, we just began to use it at work 👍 

---

I just wanted to share with you the onboarding process that was a little bit funky 😄 

Process to reproduce:

- a collegue of mine created an account + organization
- he invites me, I received an /invitation link
- the invitation link redirects to /login, first why not /register?
- then after clicking /register (via github), I did not saw that I was already part of an organization and the GUI invits me to create an organization, I had to close this page and open the https://app.repman.io to see that I am in the org actually

Obviously, I can propose/make some changes if you found this relevant 😃 

Many thanks,

**Comment by akondas** [comment]
Sure, we will gladly accept the improvement of this flow. What do you propose as a solution?

**Comment by noniagriconomie** [comment]
@akondas Hi, thanks for your reply

2 things as the `/user/invitation` is protected by the firewall right now:

- either inform the user clicking its invitation link to first register or login then to accept the invitation

this could be changed by rephrasing the email content for example

```
XXX has invited you to use Repman to collaborate with them. Create an account first or login and then use the button below to accept invitation and get started with XXX organization.
```

- or perhaps this url could be allowed as non logged in like the reset password url
https://github.com/repman-io/repman/blob/9da2e58375dd9417da558401d7a5f2dabf71cd42/src/Controller/Organization/MembersController.php#L55 

The user receiving this invitation link and clicking it (and after doing the actual job) can be then redirected to the organization (default) or login (with a flash message telling him the invitation was successful) and should login with the same email for example

**Comment by akondas** [comment]
I think that the best solution would be to add an invitation token to the session and check if this token exists after successful logging in / registration and if so, redirect the user to the path `organization_accept_invitation`. What do you think about it?

**Comment by noniagriconomie** [comment]
@akondas sound great yes, I will be glad to try this soon and propose a PR
