### ISSUE TITLE
Warning on Upgrade 1.1.0 to 1.2.1

### ISSUE THREAD

**Issue by temp** [repman-io/repman#417]
When I do a docker-composer up I can see:

```
app_1       |  [WARNING] Some commands could not be registered:
app_1       |
app_1       | In Buddy_Repman_KernelProdContainer.php line 5703:
app_1       |
app_1       |   Class 'Buddy\Repman\Service\Dist\Storage\FileStorage' not found
```

Didn't see anything related in the UPGRADE-docs, did I miss something?

**Comment by akondas** [comment]
It looks like you need to clear the cache, maybe when restarting the docker we are not doing it correctly?

**Comment by akondas** [comment]
Hello @temp is it possible for you to check the master branch version. I would like to know if our fix has solved this problem. I will be grateful for your feedback. Thanks :wink:

**Comment by temp** [comment]
@akondas uh, I already did a manual clear cache, und it worked fine. Since I'm already on 1.2.1, I'd have to downgrade to 1.1.0 again... Any other volunteers? :-D

**Comment by akondas** [comment]
No downgrade needed. Thanks, we'll test it ourselves.

**Comment by temp** [comment]
I can restart the stack, if this is sufficient. Haven't restarted it after the cache-clear. I'll try.

**Comment by temp** [comment]
Restart worked fine, no warnings.
