### ISSUE TITLE
[BUG] 404 error when package version is dev-master

### ISSUE THREAD

**Issue by slappyslap** [repman-io/repman#421]
### Configuration
Repman => 1.2.1
Private gitlab => 13.2.2 
php => 7.4
composer => 2.0.9

### The bug
We have a private package hosted in a self-host Gitlab (myvendor/mypackage for example)
When we run : composer require myvendor/mypackage:dev-master
Composer tries to retrieve the dist package from Repman via this URL :
https://organization.repo.repman.domain.com/dists/myvendor/mypackage/dev-master/XXXXXX.zip (where XXXXXX is the commit hash)

Repman answers with a 404 error. After some investigations, we found that Repman is looking for a zip file with this path :
/var/www/repman/shared/var/repo/organization/dist/myvendor/mypackage/dev-master_XXXXXX.zip
but in reality only this file exists :
/var/www/repman/shared/var/repo/organization/dist/myvendor/mypackage/9999999-dev_XXXXXX.zip

It seems related to a Composer issue :
[[2.0][RFC] Stop normalizing dev-master as 9999999-dev](https://github.com/composer/composer/issues/8323)

We add in Service/Dist.php => version() a condition to translate dev-master to 999999-dev.

Is this condition the better solution or it needs to be corrected in an another function ?

**Comment by akondas** [comment]
Thanks for reporting. I would love to see the pull request with changes. From this description it appears that your approach should be correct.
