### ISSUE TITLE
this version doesn't exist: github

### ISSUE THREAD

**Issue by vidyli** [repman-io/repman#427]
I got this error , when I try login via github oauth.

```
this version doesn't exist: github
```

this is a self hosted repoman.

**Comment by akondas** [comment]
Please check if this env vars are configured correctly:
```
OAUTH_GITHUB_CLIENT_ID=
OAUTH_GITHUB_CLIENT_SECRET=
```
From: https://github.com/settings/developers

I would also need to know where this error occurs exactly.
