### ISSUE TITLE
API not working?

### ISSUE THREAD

**Issue by binaryfire** [repman-io/repman#439]
Hi guys

I've been trying to add packages via the API. Authentication works and and the POST request goes through, but in the Repman UI it shows the following error:

```
SYNCHRONISATION ERROR
Error: Failed to execute git clone --mirror 'git@gitlab.com:my/repo.git' '/home/repman/.composer/cache/vcs/git-gitlab.com-my-repo.git/'

Cloning into bare repository '/home/repman/.composer/cache/vcs/git-gitlab.com-my-repo.git'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Logs:
Failed to clone the git@gitlab.com:my/repo.git repository, try running in interactive mode so that you can enter your credentials

```

However, when I try and add the package manually (via the UI) everything works. So I'm assuming it's some kind of bug with the API?

Cheers

**Comment by akondas** [comment]
In fact, there is one difference in the code. We will check it and I will come back with the answer and any possible correction.

**Comment by binaryfire** [comment]
@akondas Thanks! One thing I was curious about... From the logs it looks like you mirror repos to your servers. Is that how Repman works? If so, how are you able to provide an unlimited service for free? Won't your storage costs be pretty high?

**Comment by akondas** [comment]
No, we don't mirror repos, we only scan for tags and branches, repman itself only stores dist files (and that's not all either, there are some optimizations there).

**Comment by karniv00l** [comment]
@binaryfire is this happening every time? can you try again - remove package from UI and add via API? 

`Host key verification failed.` - if remote host key has changed this should fail every time (https://github.com/repman-io/repman/blob/master/Dockerfile#L44)

**Comment by binaryfire** [comment]
@karniv00l Yes happening ever time. I just confirmed it again. Adding the GitLab repo via the UI is successful.

I then removed the package in the UI and tried re-adding it via the API using:

```
curl -sS --location --request POST 'https://app.repman.io/api/organization/myorg/package' \
--header 'X-API-TOKEN: mysecrettoken' \
--header 'Content-Type: application/json' \
--data '{"repository":"https://gitlab.com/pathto/myproject.git","type":"git","keepLastReleases":0}') 
```

This is the API response:
{"id":"9ebaf6cd-5e49-4a7c-ba8e-a859d127e06e","type":"vcs","url":"https:\/\/gitlab.com\/pathto\/myproject.git","name":null,"latestReleasedVersion":null,"latestReleaseDate":null,"description":null,"lastSyncAt":null,"lastSyncError":null,"webhookCreatedAt":null,"isSynchronizedSuccessfully":false,"scanResultDate":null,"scanResultStatus":"pending","lastScanResultContent":[],"keepLastReleases":0}

And when I check in the UI, the package is there but shows a sync error as described in my original comment.

I've also found another bug- the "Unlink Gitlab" button in the "Profile" page doesn't work. I wanted to try unlinking and then re-linking Gitlab to see if it helped.

**Comment by karniv00l** [comment]
payload should look like this:

```json
{
    "repository": "patho/myproject",
    "type": "gitlab",
    "keepLastReleases": 0
}
```

**Comment by binaryfire** [comment]
Ah maybe that's why! It'd be good to add that to the documentation at https://repman.io/docs/api/. There's currently no info on the format of the payload.

Unfortunately I can't test again because of this bug: https://github.com/repman-io/repman/issues/440

**Comment by binaryfire** [comment]
@karniv00l Success! It was the payload format. Thanks a lot for your help. I'm marking this as closed. Definitely worth updating the documentation with this info ;)

**Comment by binaryfire** [comment]
You could also add some error checking to the API (so it returns a message if the payload format is incorrect).

**Comment by karniv00l** [comment]
> You could also add some error checking to the API (so it returns a message if the payload format is incorrect).

Format and all fields are validated, but you put type: `git` instead of `gitlab` for your private repo, so Repman didn't use your GitLab credentials
