### ISSUE TITLE
Bug with "Unlink Gitlab" in profile 

### ISSUE THREAD

**Issue by binaryfire** [repman-io/repman#440]
Hi guys

The "Unlink Gitlab" button in the "Profile" page doesn't work. I wanted to try unlinking and re-linking Gitlab to see if it helped with my sync errors but clicking the button doesn't disconnect from Gitlab.

So I deleted the Repman application from my Gitlab.com account instead. Repman then showed the following message:

`
Failed to fetch repositories (reason: Token was revoked. You have to re-authorize from the user.). Please try again. If the problem persists, try to remove Repman OAuth application from your provider or unlink Gitlab integration in your Profile and try again.`

But it's still showing as linked to Gitlab in the profile screen.

**Comment by akondas** [comment]
Are you using the self hosted version? Do you see any error while removing the token? I have personally checked the removal and there should be no problem with that (our instance). 

![Screenshot from 2021-04-07 07-19-04](https://user-images.githubusercontent.com/8239917/113814171-8ac1fe00-9771-11eb-8c31-e04aad812c6e.png)

**Comment by akondas** [comment]
After removing the token, the project you added remains and therefore an error and a request to re-auth the token.

**Comment by binaryfire** [comment]
@akondas It's the cloud version (your instance). Maybe a bug with my account? Here's a video:

https://zapzap.dubb.com/v/e7fBrq

**Comment by akondas** [comment]
I have a suspicion that this could be JavaScript fault. Deletion takes place via a redirection from this modal. Maybe there is a problem with this in your browser. Can you see in the JS console if there are any bugs?

```twig
            <button
                    class="btn btn-danger"
                    type="button"
                    data-target="confirmation"
                    data-action="{{ url('user_remove_oauth_token', {"type": token.type}) }}"
                    data-method="DELETE"
            >
                Unlink {{ token.type|capitalize }}
            </button>
```

**Comment by binaryfire** [comment]
Not getting any errors in the console except this (on page load):

user:1 [DOM] Found 3 elements with non-unique id #_token: (More info: https://goo.gl/9p2vKq) 
<input type=​"hidden" id=​"_token" name=​"_token" value=​"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">
<input type=​"hidden" id=​"_token" name=​"_token" value=​"yyyyyyyyyyyyyyyyyyyyyyy">
<input type=​"hidden" id=​"_token" name=​"_token" value=​"zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz">​

No errors on click either.

**Comment by binaryfire** [comment]
Ok, just tried with Edge and it worked (same error about non-unique IDs in the console, so I doubt it was that). 

Strange that it wasn't working in Chrome...

**Comment by akondas** [comment]
Probably your browser is blocking the "DELETE" request from within JS, maybe because of some add-on. If you have more information, we will gladly accept it to fix this problem.

**Comment by akondas** [comment]
I close because of the lack of further information. If necessary, please open issue again :wink:
