### ISSUE TITLE
Packages from git with ssh

### ISSUE THREAD

**Issue by fetzi** [repman-io/repman#45]
I want to add packages from an internal git repository with ssh, so I tried to add an ssh key to the app container and also set the `GIT_SSH_COMMAND` env variable in `.env.docker`.

But then I recognized that the ssh binary is missing in the container as well. Do you have this feature on your roadmap or any plans to support repositories via ssh?

**Comment by akondas** [comment]
It will be a common case so I think we can take care of it even now.

**Comment by akondas** [comment]
This is a partial solution, we have other variants planned in the roadmap that will allow you to add or generate a key via the UI panel.
