### ISSUE TITLE
preg_match expects parameter 2 to be string, null given

### ISSUE THREAD

**Issue by pawel-detka** [repman-io/repman#450]
Greetings,
May I as for support regarding this error in repman.io ?

```
Error: preg_match() expects parameter 2 to be string, null given
Logs:
Reading composer.json of module/module-example-pricing (1.0.9)
Importing tag 1.0.9 (1.0.9.0)
Reading composer.json of module/module-example-pricing (1.0.8)
Importing tag 1.0.8 (1.0.8.0)
Reading composer.json of module/module-example-pricing  (1.0.7)
Importing tag 1.0.7 (1.0.7.0)
Reading composer.json of module/module-example-pricing  (1.0.6)
Importing tag 1.0.6 (1.0.6.0)
Reading composer.json of module/module-example-pricing  (1.0.5)
Importing tag 1.0.5 (1.0.5.0)
Reading composer.json of module/module-example-pricing  (1.0.4)
Importing tag 1.0.4 (1.0.4.0)
Reading composer.json of module/module-example-pricing  (1.0.3)
Importing tag 1.0.3 (1.0.3.0)
Reading composer.json of module/module-example-pricing  (1.0.2)
Importing tag 1.0.2 (1.0.2.0)
Reading composer.json of module/module-example-pricing  (1.0.1)
Importing tag 1.0.1 (1.0.1.0)
Reading composer.json of module/module-example-pricing  (1.0.0)
Importing tag 1.0.0 (1.0.0.0)
Reading composer.json of module/module-example-pricing  (master)
Importing branch master (dev-master)
```

[https://imgur.com/a/5e4e1pZ](https://imgur.com/a/5e4e1pZ)

**Comment by ladushki** [comment]
I have the same issue

**Comment by akondas** [comment]
Please check if your composer.json file has `name` field, for example:
```json
{
    "name": "repman-io/repman",
}
 ```

If not, then we probably don't handle this bug correctly. A message should appear that this field is required. Without a name, we cannot add a package to the registry.

**Comment by pawel-detka** [comment]
Hi @akondas 
I've checked all branches/tags for composer.json file - name is correct.
This package was already in package list, las tag broke it.

**Comment by ladushki** [comment]
I also have a correct name. Which worked so far.

**Comment by pawel-detka** [comment]
Different package, same issue
[https://imgur.com/a/SkPVRk4](https://imgur.com/a/SkPVRk4)

**Comment by akondas** [comment]
Are you able to provide a repository or create one that also has this bug? I'd like to reproduce it to fix it.

**Comment by pawel-detka** [comment]
Sorry, those repositories are private and dedicated for specific project, without NDA I cannot do that.

**Comment by ladushki** [comment]
MIne are private too

**Comment by akondas** [comment]
It will look as if the package name was missing from the last stable release:
```php
            $name = $latest->getPrettyName();
            if (preg_match(Package::NAME_PATTERN, $name, $matches) !== 1) {
                throw new \RuntimeException("Package name {$name} is invalid");
            }
```

**Comment by pawel-detka** [comment]
I've double checked that, in both packages name was correct in all releases. Also I tried to remove package and add fresh one - the same issue.

**Comment by ladushki** [comment]
I have done the same. The package was fine for many days, until today. I also tried to remove and add.

**Comment by akondas** [comment]
@ladushki have you made any changes to the code? Did the sync just stop working? 

Maybe something in the API has changed. Anyway, from what I can see it's BitucketDriver's fault, I don't know why, but it returns an unnamed package.

**Comment by ladushki** [comment]
I have a name though...
![image](https://user-images.githubusercontent.com/3170511/117452804-1c24bb80-af3c-11eb-81a0-51ab114bb253.png)

**Comment by akondas** [comment]
Ok, #451 was deployed. Please try to run synchronization again. You will see revision number with missing name:
![Screenshot from 2021-05-07 14-52-11](https://user-images.githubusercontent.com/8239917/117452661-509c7580-af44-11eb-9adb-6376d12f5f9a.png) 
Maybe it will help somehow. 

The second thing is that we are still waiting for the composer update, because we use the old version for synchronization ... it can also be this fault.

**Comment by ladushki** [comment]
I have just tried and it works now :)  Thanks!

All the best,
Larissa

**Comment by akondas** [comment]
I'm beginning to suspect this is a temporary API hiccup. Something similar has happened once before: #202

**Comment by pawel-detka** [comment]
Thank you @akondas, it is working now.
