### ISSUE TITLE
Invalid credentials from self-hosted

### ISSUE THREAD

**Issue by antiseptikk** [repman-io/repman#465]
I am having problems with authorization.

When I fetch (private) organization repository with composer I have always : 

    [Composer\Downloader\TransportException]
      Invalid credentials for 'https://org.repo.repman.**/packages.json', aborting.

I try to add token with CLI and directly in `~/.composer/auth.json` file in `http-basic` section.

```
{
    "http-basic": {
        "org.repo.repman.**": {
            "username": "token",
            "password": "***"
        }
    }
}
```

It's working with anonymous access enabled.

Repman run in self-hosted server, with Apache and php-fpm 7.4

**Comment by karniv00l** [comment]
Try debugging with curl. Can't help much with Apache though.

```bash
curl https://your-org.repo.repman.**/packages.json -u token
```

**Comment by antiseptikk** [comment]
I try to debug with curl and postman and in get the same error.

```
{"message":"Invalid credentials."}
```

**Comment by antiseptikk** [comment]
Yeah !

I add this line in my `.htaccess`

```
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
```

Thanks for the help it can help other people.
