### ISSUE TITLE
Package Dependencies gets duplicated

### ISSUE THREAD

**Issue by giggsey** [repman-io/repman#468]
Creating so I can remember to investigate further.

Created a new package today, and pushed twice. The original deps have now duplicated. I think the issue is that there is no stable release of the package yet, so maybe the code clearing the old deps isn't getting a chance to run.

**Comment by dheineman** [comment]
you beat me to creating an issue by 15 minutes :)

i ran into the same problem when performing the update action on an existing package which does not have a stable version.

**Comment by akondas** [comment]
I confirm that I also managed to reproduce this problem.

**Comment by akondas** [comment]
Hello, fix is on its way. After another sync, everything will repair itself.
(CC @KapitanOczywisty)
