### ISSUE TITLE
Bump Symfony to 5.3

### ISSUE THREAD

**Issue by akondas** [repman-io/repman#480]
Currently blocked by https://github.com/nelmio/NelmioApiDocBundle/issues/1807

**Comment by GuilhemN** [comment]
[4.3.0](https://github.com/nelmio/NelmioApiDocBundle/releases/tag/v4.3.0) is now released :)

**Comment by akondas** [comment]
Thanks for update :+1:

**Comment by akondas** [comment]
Ok, works, but now I need to update all deprecated features:
- [ ] security: https://github.com/symfony/symfony/blob/5.4/UPGRADE-5.3.md#security
- [ ] session: https://github.com/symfony/symfony/blob/5.4/UPGRADE-5.3.md#frameworkbundle
