### ISSUE TITLE
release tags not synchronized

### ISSUE THREAD

**Issue by vidyli** [repman-io/repman#481]
*  github webhook, I can see delivered,   when I created a new tag v1.2.1, repman return 202 response,
*  but no  `v1.2.1` in `Available versions` in the package

Steps to reproduce

* create a release tag v1.0.0 in github
* then you can see the v1.0.0 in repman
* then edit that release to v1.0.1 in github
* Now, no v1.0.1 found, even you remove the package from repman, add it again, we can never see any releases anymore.

One working way to resolve

I did all these steps, I don't know which one actually  solve the problem.

* remove all packages in repoman including dist,  metadata, also remove the package from table(organization_package)
* remove the package in github
* then add the package to repman again.

**Comment by akondas** [comment]
Hello, if you edit release (not tag), this change will not be visible. You need to distinguish release from the tag. Repman supports the tag versioning (tag != release in GitHub terminology).

**Comment by vidyli** [comment]
@akondas , I see, thanks
