### ISSUE TITLE
Docker: docker compose up not working / invalid docker-compose.yml

### ISSUE THREAD

**Issue by ThomasBoom89** [repman-io/repman#519]
Hello :)

OS: Linux
Docker version: 20.10.9
Docker compose version: 2.0.1

I wanted to test the project via docker setup.
Did a _git clone_ and without any changes to the repo _docker compose up_ in the root of the project, resulted in the following error message: 
**service "nginx" refers to undefined volume docker-logs-nginx/: invalid compose project**

In search of a solution I found a trailing slash at the nginx service definition for docker-logs-nginx volume. In the volume definition there is no trailing slash. In commit 4e1226e58925b22c430090f3800fd85eb1514018 there was a change from mounts to volume, maybe nobody reported this error or it may be a bug in newer docker version. Removing the slash fixed the error and everything run up. Is a PR welcome?

PS: thanks for this amazing project!

**Comment by karniv00l** [comment]
Thanks 👍 Looks like a typo, PR is welcome

**Comment by ThomasBoom89** [comment]
#520
