### ISSUE TITLE
Query: Azure DevOps Support

### ISSUE THREAD

**Issue by nedwors** [repman-io/repman#551]
Hi!

Thank you for this amazing service, we have been using it without any issues for around a year now.

We host our code on Azure DevOps, so at the moment we are running mirror repositories on GitHub to facilitate Repman. To have baked in support for DevOps would be fantastic.

I've not looked massively at the code base, but here are my questions:

1. Would you be open to accepting a PR (or however many are needed) to add support for Azure DevOps?
2. Are there any technical issues you know of that have maybe prevented this happening already?

No problemo either way, just wanted to reach out and gauge your feelings about support for Azure DevOps 😃

**Comment by akondas** [comment]
Hi @nedwors 
Thanks for feedback. 

ad. 1: absolutely yes
ad. 2: no (only a lack of time and my experience with azure) :wink: 

If you have any further questions, please write.

**Comment by nedwors** [comment]
@akondas ok that's good to know! We will have a think as to whether we can mix this into our development cycles, I'm sorry we can't promise anything. But thank you for being open to the idea and available to assist ❤️
