### ISSUE TITLE
Allow disabling security scan for certain projects

### ISSUE THREAD

**Issue by giggsey** [repman-io/repman#555]
We have some old projects within Repman that are EOL/not used, which have security vulnerable dependencies.

It'll be useful to allow disabling security scans for projects (default to on).

**Comment by shochdoerfer** [comment]
I'd be interested in this, too. Also, I'd happily start hacking on this feature if it is clear what is wanted.

**Comment by alamirault** [comment]
In this case, I think it a good thing

**Comment by shochdoerfer** [comment]
Will start hacking on this soonish.
