### ISSUE TITLE
Organization members

### ISSUE THREAD

**Issue by akondas** [repman-io/repman#56]
Currently, the organization has only the owner - the user who created it. 

Members - will give the opportunity to manage people in the organization, send invitations and remove them.

Features:
- [ ] invite by e-mail
- [ ] two manage scope: member, admin

**Comment by akondas** [comment]
Then let's try to write the permissions:

**Member**
- manage packages (can't remove)
- see organization tokens

**Admin**
- can remove package
- manage tokens
- organization configuration 

**Owner**
- remove organization
- transfer ownership

**Comment by akondas** [comment]
Now is time form flow:

- Owner creates invitation
  - choose a role
  - invitation has a finite period of validity
- User accepts invitation
  - already exist: click link in e-mail 
  - new users: creates account

**Comment by karniv00l** [comment]
looks good

**Comment by akondas** [comment]
:tada: released in [0.2.0](https://github.com/repman-io/repman/releases/tag/0.2.0)
