### ISSUE TITLE
Unable to add new packages on repman.io

### ISSUE THREAD

**Issue by jorisvaesen** [repman-io/repman#565]
Adding a new package on repman.io keeps endless synchronizing.
Latest zip of a current package (dev-master) is corrupt and cant be unzipped by composer.
Webhooks are received but package doesn't get updated, also not after a forced updated.

It looks like things are going wrong on Repman.io at the moment.

As I didn't find any status page I opened this issue.

**Comment by Jarzebowsky** [comment]
Happened the same on my end. It doesn't add new packages but also doesn't fetch new tags for updating packages already added.

**Comment by akondas** [comment]
There is a large queue of tasks, everything should be back by the hour. Sorry for problems.

**Comment by akondas** [comment]
ok, the queue is stabilized now, everything should work
