### ISSUE TITLE
Api docs not showing up

### ISSUE THREAD

**Issue by rizkhal** [repman-io/repman#569]
https://repman.io/docs/api/

![Screenshot from 2022-02-28 00-50-30](https://user-images.githubusercontent.com/24653114/155889544-3ca3e7a3-8d72-4c3c-ad20-87976f650d6b.png)

**Comment by xvilo** [comment]
It appears the viewer only supports 2.0 and 3.0.x versions, but the specification is in `"openapi": "3.1.0",`.
