### ISSUE TITLE
Pulling in github package gets stuck.

### ISSUE THREAD

**Issue by danharper83** [repman-io/repman#625]
I have two packages that are just stuck at the synchronising part form github. One has been there for a few weeks and I have since recreated it with the same repo. I tried to create the other earlier and it's doing the same thing.

Organisation name is hrpr

Thanks Dan

**Comment by akondas** [comment]
I will take a look but workers are working correctly ... maybe some kid of bug :thinking:

**Comment by akondas** [comment]
Looks like you have duplicated packages in your organization ... please remove them and add again with different name

**Comment by akondas** [comment]
Reopen if thats not the case :wink:
