### ISSUE TITLE
Versions stopped updating suddenly

### ISSUE THREAD

**Issue by pavemolc-circunomics** [repman-io/repman#630]
Hey! Today the versions of my package stopped updating suddenly. Github webhook call history says that call were successful. I also tried to synchronize manually, but nothing happens.

**Comment by Noaber** [comment]
Same here, new commits aren't synced.

**Comment by akondas** [comment]
There was a little problem today with an overflowing disk so things might not be syncing for a while, but for now everything should be working fine. Alternatively, you can wait a while until the workers catch up with the backlog. I can see that there is still a bunch of messages in the queue.

**Comment by pavemolc-circunomics** [comment]
Thank you!
