### ISSUE TITLE
Login and download issues on repman.io

### ISSUE THREAD

**Issue by jorisvaesen** [repman-io/repman#634]
It is currently impossible to log in to repman.io and installing repman.io hosted packages through composer results in failures.

```
In ZipDownloader.php line 209:
                                                                                   
  '/path/to/vendor/composer/tmp-42f84de0b5679ed80ce8759f249288d9.  
  zip' is not a zip archive.    
```

**Comment by rafaellaurindo** [comment]
I'm also having trouble pulling a repository from repman.

**Comment by arosenhagen** [comment]
For me it's: 
`Failed downloading XXX, trying the next URL (0: curl error 92 while downloading https://XXX.repo.repman.io/dists/XXX/XXX/dev-main/XXX.zip: HTTP/2 stream 91 was not closed cleanly: INTERNAL_ERROR (err 2))`

**Comment by vtsykun** [comment]
Password reset also does not works: "The CSRF token is invalid. Please try to resubmit the form."

**Comment by Rindula** [comment]
Login and Signup also don't work

**Comment by joemugen** [comment]
Having issue when trying to install a package via Composer too, I think it's linked:

```
In CurlDownloader.php line 365:
                                                                                                 
  [Composer\Downloader\TransportException]                                                       
  curl error 92 while downloading https://xxx.repo.repman.io/packages.json: HTTP/2 strea  
  m 0 was not closed cleanly: INTERNAL_ERROR (err 2)   
```

**Comment by akondas** [comment]
Sorry, full disk error strikes again :disappointed:, workers will probably needs coupel minutes to catchup with work

**Comment by akondas** [comment]
Please reopen if needed, right now should work.
