### ISSUE TITLE
Is this a dead project?

### ISSUE THREAD

**Issue by jonnylink** [repman-io/repman#644]
I hate to ask this question because I know it's somewhat thankless opensource work, but I have to know. Is this project still active?

Noticed a pretty big bug where repman can't find a stable version that's been around for over a year with a PR to fix it for nearly as long. There also hasn't been a release in over a year.

Is there anyone working on this still?

* https://github.com/repman-io/repman/issues/514
* https://github.com/repman-io/repman/pull/562

**Comment by thomasnordahl-dk** [comment]
+1 for this - I'm wondering the same.

**Comment by Radiergummi** [comment]
I guess since @akondas left Buddy, there probably isn't any active work on Repman anymore...

**Comment by thomasnordahl-dk** [comment]
Thank you for the information, that is really good to know :+1:

**Comment by akondas** [comment]
but that doesn't mean the project is dead :sweat: , I'll try to catch up this weekend and review all pull requests :crossed_fingers:

**Comment by jonnylink** [comment]
Glad to hear it's not dead! Just came to it and aside from these rough spots it seems great. Nice work.

**Comment by akondas** [comment]
I'm closing but please reopen if needed

**Comment by moay** [comment]
@akondas Sorry, reopening as is needed. Any plans to go further with this?
