### ISSUE TITLE
Service unavailable

### ISSUE THREAD

**Issue by marcospassos** [repman-io/repman#672]
We are currently experiencing issues fetching package metadata. Is the service experiencing an outage?

**Comment by jacerider** [comment]
Having the same issue. Also cannot log in.

**Comment by ProxiBlue** [comment]
Yes, there seems to be an issue with http2 protocol on the servers

curl error 92 while downloading https://xxxxxxxx.repo.repman.io/packages.json: HTTP/2 stream 65 was not closed cleanly: INTERNAL_ERROR (err 2)

**Comment by naseefpv** [comment]
Yes, Cannot login or publish the app

**Comment by adaluppa** [comment]
The service is back to normal now.

**Comment by arronmoss** [comment]
doesnt look back to normal, Im only showing 10 of my 90 packages available via composer show so all our CI/CD pipellines are falling over.

**Comment by akondas** [comment]
Small worker issue, task queue is staring to catch up. Sorry for problems.

**Comment by ProxiBlue** [comment]
Just as a note, a day later, I still found all my packages come back 404.

```
 Problem 1
    - Root composer.json requires elgentos/magento2-link-guest-orders-to-customer ^1.0, found elgentos/magento2-link-guest-orders-to-customer[1.0.0] in the lock file but not in remote repositories, make sure you avoid updating this package to keep the one from the lock file.
    -
40 more like this.
```

using the script I supplied above fixed it all up.

**Comment by astersnake** [comment]
> Small worker issue, task queue is staring to catch up. Sorry for problems.

You should close the issue when it no longer occurs, as we are still receiving the 404 error.

**Comment by treestonemedia** [comment]
@akondas this is still happening :(

**Comment by ProxiBlue** [comment]
If you are getting 404's, use the script I supplied above, it fixes the 404 issues, and you can go on.

**Comment by treestonemedia** [comment]
@ProxiBlue Yes, they're all on the same ORG_Name
I looked at the code and both scripts do the same thing, I couldn't run yours because I don't have `http` installed, i get a `command not found`

**Comment by treestonemedia** [comment]
@ProxiBlue I installed `http` and ran your script - same results
