### ISSUE TITLE
MySQL as persistent storage

### ISSUE THREAD

**Issue by sadortun** [repman-io/repman#71]
Hi,

In your requirements you mentioned `PostgreSQL 11`, will this project work with Mysql ? 

Thanks,
Samuel

**Comment by akondas** [comment]
Unfortunately not. At present, migrations are created with PostgreSQL in mind. However, we provide solutions for self-installation of PostgreSQL (Ansible) and ready docker images (https://repman.io/docs/standalone/#docker-installation) so this should not be a problem.
