### ISSUE TITLE
Database initialization

### ISSUE THREAD

**Issue by sadortun** [repman-io/repman#72]
Hi!

Could you please add in the readme instruction on how to initialize the database ?

Seems that
- bin/console doctrine:migrations:migrate               
is not enough

I receive the following exception when creating packages

```
SQLSTATE[42P01]: Undefined table: 7 ERROR: relation "messenger_messages" does not exist LINE 1: INSERT INTO messenger_messages (body, headers, queue_name, c... ^
```

**Comment by sadortun** [comment]
Seems i was missing  `bin/console messenger:setup-transports`

**Comment by akondas** [comment]
This command is in both installation variants: Ansible and Docker, but I added it to README too :wink:  in #78
