### ISSUE TITLE
Configuration issue/question

### ISSUE THREAD

**Issue by sadortun** [repman-io/repman#76]
Hi @akondas 

I have a few config questions for you: 

### Question 1
In the home page, you have config info for the Proxy

![image](https://user-images.githubusercontent.com/794449/79943200-4c371480-8436-11ea-8656-11c0e6db179b.png)

And under the Organisation, repo for the organisation 
![image](https://user-images.githubusercontent.com/794449/79943256-6d980080-8436-11ea-8671-05da1771e38e.png)

If i understand correctly, both  `org.repo......` and `repo....` are needed. Is it correct ?

### Question 2 
I have 30+ packages in repman, but if i take a look inside the composer cache, the 

`.../Composer/repo/https---org.repo.repman.example.com/packages.json`  only contains 8 packages

When i do a `composer update`, composer report that `-> no matching package found.` for a few packages

(i also tried to Update, the package, and to delete and re-add them)

Is it normal ?

**Comment by akondas** [comment]
Ad 1.
`repo.repman.your.domain` - this url is only for packagist proxy
`org.repo.repman.your.domain` - this url is for your organization packages, you need add token configuration for each host 

Ad 2.
I would need more details about this. Repman (at this moment) stores only distributions files for each package. This has nothing to do with composer cache.

**Comment by sadortun** [comment]
Thanks!

For # 2,  I am not sure what info to provide you. 

I've done some more tests, for example, i created a new organisation and added the packages. and they are all present in the `packages.json`

Let me know if you have any ideas!

**Comment by sadortun** [comment]
Ok ! I've found the cause of the issue.

Repman is running in a k8s cluster, and data on disk is shared between pods using the ENV variables.

```
PROXY_DIST_DIR=/var/www/repman/share/proxy/
PACKAGES_DIST_DIR=/var/www/repman/share/dist/
```

When the pod restart,  all previous existing packages that were listed in `https://org.repo.example.com/packages.json` dissapear. and you need to delete in the UI the package, and re-add it.

Still looking for the cause of the issue.

**Comment by sadortun** [comment]
I've found the issue for # 2, i had an incorect path in my config.

**Comment by akondas** [comment]
FYI, we have plans to support deployment on k8s :wink:
