### ISSUE TITLE
Not detecting all versions of package

### ISSUE THREAD

**Issue by georgeboot** [repman-io/repman#83]
We use the cloud version.

I synced a GitHub repo, and according to repman, the latest version is `1.5.1`. However, the package already has some new releases:

<img width="1023" alt="Schermafbeelding 2020-04-22 om 13 51 00" src="https://user-images.githubusercontent.com/884482/79978520-57bf2580-84a0-11ea-9aa9-cd0cea623563.png">

What is going wrong?

**Comment by akondas** [comment]
Latest version detection mechanism. I suppose the packages have been synchronized correctly only the latest version has been badly detected. I will try to reproduce it and add a fix for this.

**Comment by georgeboot** [comment]
Something I noticed now is that the version numbers are not correctly in order (`1.5.0` comes after `1.5.1`). Could this be related?

**Comment by akondas** [comment]
This switch is the problem, but I think we can handle that.

**Comment by akondas** [comment]
I wonder whether to change this column to `Last version` and just show the last published version
