### ISSUE TITLE
404 when downloading zip

### ISSUE THREAD

**Issue by georgeboot** [repman-io/repman#84]
When installing, I get the following error:

`Installing companyname/packagename (dev-feature/skip-triggers 089c4aa): Downloading (failed)
 Failed, trying the next URL (404: The "https://companyname.repo.repman.io/dists/companyname/packagename/b9073f99786cfba24db9854fc115c959/089c4aa941b8c68b073dbc39b20fca32016ac70c.zip" file could not be downloaded (HTTP/1.1 404 Not Found)) Loading from cache`

What might be going wrong here? The package is fully synced up, I added the token to my composer and added the repositories section to my `composer.json`.

**Comment by akondas** [comment]
Which package version is entered in the composer.json file?

**Comment by georgeboot** [comment]
`"companyname/packagename": "dev-feature/skip-triggers"`

**Comment by akondas** [comment]
I will try to reproduce it and come back with an answer. I suppose this is some missing case and we will be able to fix it.

**Comment by akondas** [comment]
I was able to reproduce it. It turned out that if the version name contains `/`, then composer returns the md5 hash instead of the version name. I work on a fix.

**Comment by akondas** [comment]
@georgeboot thanks for feedback. You will need to run update again to fix your issue, but for new packages, this problem will not occurs again.
