### ISSUE TITLE
Repman behind proxy

### ISSUE THREAD

**Issue by sadortun** [repman-io/repman#90]
In https://github.com/repman-io/repman/blob/master/src/Controller/ProxyController.php#L34, The URL generated do not use APP_URL_SCHEME and APP_HOST

This have for effect in the situation where repman is behind a proxy that handle SSL (k8s Cert-manager Ingress), the router sees incoming request as `HTTP` instead of `HTTPS`.

There is two solution to that:
1) Using APP_HOST and APP_URL_SCHEME to generete the URLs instead of `$this->generateUrl('index', [], RouterInterface::ABSOLUTE_URL)`

2) Tell the router that we are indeed using SSL
```patch
 public/index.php | 5 +++++
 1 file changed, 5 insertions(+)

diff --git a/public/index.php b/public/index.php
index 6eddf35..04d4b95 100644
--- a/public/index.php
+++ b/public/index.php
@@ -6,6 +6,11 @@ use Symfony\Component\HttpFoundation\Request;

 require dirname(__DIR__).'/config/bootstrap.php';

+// If we are behing a load-balancer that takes care of HTTPS, we need to set the right headers
+if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') {
+    $_SERVER['HTTPS'] = 'on';
+}
+
 if ($_SERVER['APP_DEBUG']) {
     umask(0000);


```

**Comment by akondas** [comment]
Second option looks ok, if only then there will be no problem with the host then we can add such a change.

**Comment by akondas** [comment]
One thing puzzles me, why this problem cannot be solved by trusted proxies? https://symfony.com/doc/current/deployment/proxies.html

**Comment by sadortun** [comment]
You are right ! I was unaware of this Symfony Config :)

**Comment by akondas** [comment]
I'm glad I could help. If there was any problem with it, please go ahead and reopen this issue
