### ISSUE TITLE
Allow for public (read-only) access in organization

### ISSUE THREAD

**Issue by akondas** [repman-io/repman#96]
This issue is a continuation of the thread from reddit:
> I mean adding a package to an organisation, and guests being able to browse and download those packages.

We could do an option in your organization's settings that would allow open access for added packages.

**Comment by sadortun** [comment]
I am not sure if this would fit in this issue but i can see 3 different access levels to access the organizations.

- Authenticated admin ( add, remove packages, add users .... )
- Authenticated users ( can only access packages )
- Anonymous  users (No authentification required to access the organizations package in read-only)

For the Anonymous access, it could probably be a checkbox `Allow Anonymous users` in the admin settings

**Comment by akondas** [comment]
These levels of access are already partially implemented by members of the organization. Only the option with anonymous access to the organization remains. I think we will do it in the next release (right after security scanner).

**Comment by akondas** [comment]
Released in https://github.com/repman-io/repman/releases/tag/0.4.0
